name: DungeonsXL
version: 2.9
main: com.dre.dungeonsxl.P
authors: [Frank Baumann]
softdepend: [Vault]
commands:
  dungeonsxl:
    description: Reference command for DungeonsXL.
    aliases: [dxl,dungeon]