name: DungeonsXL
main: io.github.dre2n.dungeonsxl.DungeonsXL
version: ${project.version}
authors: [Frank Baumann, Milan Albrecht, Tobias Schmitz, Daniel Saukel]
description: ${project.description}
website: ${project.url}
softdepend: [BlueRoseCommons, CommandsXL, Vault, MythicMobs]
commands:
  dungeonsxl:
    description: Reference command for DungeonsXL.
    aliases: [dxl,dungeon]
permissions:
  dxl.break:
    default: op
  dxl.chat:
    default: true
  dxl.chatspy:
    default: op
  dxl.create:
    default: op
  dxl.edit:
    default: op
  dxl.enter:
    default: op
  dxl.escape:
    default: true
  dxl.game:
    default: true
  dxl.group:
    default: op
  dxl.group.admin:
    default: op
  dxl.help:
    default: true
  dxl.invite:
    default: op
  dxl.leave:
    default: true
  dxl.list:
    default: true
  dxl.lives:
    default: true
  dxl.main:
    default: true
  dxl.msg:
    default: op
  dxl.play:
    default: op
  dxl.portal:
    default: op
  dxl.reload:
    default: op
  dxl.save:
    default: op
  dxl.test:
    default: op
  dxl.uninvite:
    default: op
  dxl.ignoretimelimit:
    default: op
  dxl.ignorerequirements:
    default: op
  dxl.sign:
    default: op
  dxl.bypass:
    default: op
  dxl.cmdedit:
    default: op
  dxl.insecure:
    default: op
