classes:
    1:
        name: Krieger
        items:
        - 276,1
        - 302,1
        - 303,1
        - 304,1
        - 305,1
        - 364,1
        hasdog: false
    2:
        name: Tank
        items:
        - 279,1
        - 310,1
        - 307,1
        - 308,1
        - 309,1
        - 364,3
        hasdog: false
    3:
        name: Jäger
        items:
        - 261,1
        - 262,128
        - 268,1
        - 298,1
        - 299,1
        - 300,1
        - 301,1
        - 364,3
        - 363,10
        hasdog: true
    4:
        name: Bogenschütze
        items:
        - 261,1
        - 262,128
        - 272,1
        - 302,1
        - 299,1
        - 300,1
        - 301,1
        - 364,3
    5:
        name: Magier
        items:
        - 298, 1
        - 315, 1
        - 373,16385,3
        - 373,16389,3
        - 373,16387,2
        - 373,16387,2
        - 373,16394,3
        - 364,8