name: DungeonsXL
main: io.github.dre2n.dungeonsxl.DungeonsXL
version: 0.10-SNAPSHOT
author: Frank Baumann
authors: [Frank Baumann, Milan Albrecht, Tobias Schmitz, Daniel Saukel]
website: http://dre2n.github.io
softdepend: [Vault, MythicMobs, CommandsXL]
commands:
  dungeonsxl:
    description: Reference command for DungeonsXL.
    aliases: [dxl,dungeon]
