name: DungeonsXL
main: com.dre.dungeonsxl.P
version: 0.8.3
author: Frank Baumann
authors: [Frank Baumann, Milan Albrecht, Tobias Schmitz, Daniel Saukel]
website: http://www.dre2n.ml
softdepend: [Vault, SpoutcraftPlugin]
commands:
  dungeonsxl:
    description: Reference command for DungeonsXL.
    aliases: [dxl,dungeon]
