name: DungeonsXL
main: com.dre.dungeonsxl.P
version: 0.9.6
author: Frank Baumann
authors: [Frank Baumann, Milan Albrecht, Tobias Schmitz, Daniel Saukel]
website: http://www.dre2n.ml
depend: [Vault]
softdepend: [Citizens, HolographicDisplays, HolographicMenus, InfernalMobs, MythicMobs]
commands:
  dungeonsxl:
    description: Reference command for DungeonsXL.
    aliases: [dxl,dungeon]
